//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewoTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SewoTranslator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutMI {
            get {
                return ResourceManager.GetString("AboutMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer:.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitMI {
            get {
                return ResourceManager.GetString("ExitMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The translator works by translating of copied text..
        /// </summary>
        public static string In_1 {
            get {
                return ResourceManager.GetString("In_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut for displaying the copied text:.
        /// </summary>
        public static string In_2 {
            get {
                return ResourceManager.GetString("In_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the text.
        /// </summary>
        public static string In_3 {
            get {
                return ResourceManager.GetString("In_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows already copied text.
        /// </summary>
        public static string In_4 {
            get {
                return ResourceManager.GetString("In_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows or hides the window:.
        /// </summary>
        public static string In_5 {
            get {
                return ResourceManager.GetString("In_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string ManualMI {
            get {
                return ResourceManager.GetString("ManualMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions and use of the translator.
        /// </summary>
        public static string ManualTitle {
            get {
                return ResourceManager.GetString("ManualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the program after the computer is turned on:.
        /// </summary>
        public static string OnSturtupSetting {
            get {
                return ResourceManager.GetString("OnSturtupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved words.
        /// </summary>
        public static string SavedWordsMI {
            get {
                return ResourceManager.GetString("SavedWordsMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMI {
            get {
                return ResourceManager.GetString("SettingsMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sewo Translator.
        /// </summary>
        public static string SewoTranslator {
            get {
                return ResourceManager.GetString("SewoTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowMI {
            get {
                return ResourceManager.GetString("ShowMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfound words.
        /// </summary>
        public static string UnfoundWords {
            get {
                return ResourceManager.GetString("UnfoundWords", resourceCulture);
            }
        }
    }
}
